# Generated by Django 5.0.7 on 2025-02-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGabrielPortifolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
